In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("/content/Admission_Predict.csv")

In [3]:
df.head(10)

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   
5           6        330          115                  5  4.5   3.0  9.34   
6           7        321          109                  3  3.0   4.0  8.20   
7           8        308          101                  2  3.0   4.0  7.90   
8           9        302          102                  1  2.0   1.5  8.00   
9          10        323          108                  3  3.5   3.0  8.60   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65  
5         1              0.90  
6         1              0.75  
7         0              0.68  
8         0              0.50  
9         0              0.45

In [4]:
df.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [5]:
len(df.columns)

9

In [6]:
df.shape

(400, 9)

In [7]:
df.isnull().sum().sum()

0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Serial No.         400 non-null    int64  
 1   GRE Score          400 non-null    int64  
 2   TOEFL Score        400 non-null    int64  
 3   University Rating  400 non-null    int64  
 4   SOP                400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           400 non-null    int64  
 8   Chance of Admit    400 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 28.2 KB


In [9]:
df.duplicated().sum().sum()

0

In [10]:
df.shape

(400, 9)

In [11]:
df.drop(columns=["Serial No."],inplace=True)

In [12]:
df.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72  
3              0.80  
4              0.65

In [39]:
x=df[["GRE Score","TOEFL Score","University Rating","SOP","CGPA","Research"]].values
y=df.iloc[:,-1].values

In [40]:
x

array([[337.  , 118.  ,   4.  ,   4.5 ,   9.65,   1.  ],
       [324.  , 107.  ,   4.  ,   4.  ,   8.87,   1.  ],
       [316.  , 104.  ,   3.  ,   3.  ,   8.  ,   1.  ],
       ...,
       [330.  , 116.  ,   4.  ,   5.  ,   9.45,   1.  ],
       [312.  , 103.  ,   3.  ,   3.5 ,   8.78,   0.  ],
       [333.  , 117.  ,   4.  ,   5.  ,   9.66,   1.  ]])

In [41]:
y

array([0.92, 0.76, 0.72, 0.8 , 0.65, 0.9 , 0.75, 0.68, 0.5 , 0.45, 0.52,
       0.84, 0.78, 0.62, 0.61, 0.54, 0.66, 0.65, 0.63, 0.62, 0.64, 0.7 ,
       0.94, 0.95, 0.97, 0.94, 0.76, 0.44, 0.46, 0.54, 0.65, 0.74, 0.91,
       0.9 , 0.94, 0.88, 0.64, 0.58, 0.52, 0.48, 0.46, 0.49, 0.53, 0.87,
       0.91, 0.88, 0.86, 0.89, 0.82, 0.78, 0.76, 0.56, 0.78, 0.72, 0.7 ,
       0.64, 0.64, 0.46, 0.36, 0.42, 0.48, 0.47, 0.54, 0.56, 0.52, 0.55,
       0.61, 0.57, 0.68, 0.78, 0.94, 0.96, 0.93, 0.84, 0.74, 0.72, 0.74,
       0.64, 0.44, 0.46, 0.5 , 0.96, 0.92, 0.92, 0.94, 0.76, 0.72, 0.66,
       0.64, 0.74, 0.64, 0.38, 0.34, 0.44, 0.36, 0.42, 0.48, 0.86, 0.9 ,
       0.79, 0.71, 0.64, 0.62, 0.57, 0.74, 0.69, 0.87, 0.91, 0.93, 0.68,
       0.61, 0.69, 0.62, 0.72, 0.59, 0.66, 0.56, 0.45, 0.47, 0.71, 0.94,
       0.94, 0.57, 0.61, 0.57, 0.64, 0.85, 0.78, 0.84, 0.92, 0.96, 0.77,
       0.71, 0.79, 0.89, 0.82, 0.76, 0.71, 0.8 , 0.78, 0.84, 0.9 , 0.92,
       0.97, 0.8 , 0.81, 0.75, 0.83, 0.96, 0.79, 0.

In [42]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [43]:
x_train

array([[301.  ,  97.  ,   2.  ,   3.  ,   7.88,   1.  ],
       [334.  , 119.  ,   5.  ,   5.  ,   9.7 ,   1.  ],
       [305.  , 112.  ,   3.  ,   3.  ,   8.65,   0.  ],
       ...,
       [325.  , 107.  ,   3.  ,   3.  ,   9.11,   1.  ],
       [326.  , 111.  ,   5.  ,   4.5 ,   9.23,   1.  ],
       [300.  , 105.  ,   1.  ,   1.  ,   7.8 ,   0.  ]])

In [44]:
x_test

array([[312.  , 103.  ,   3.  ,   3.5 ,   8.78,   0.  ],
       [300.  , 100.  ,   3.  ,   2.  ,   8.66,   1.  ],
       [324.  , 112.  ,   4.  ,   4.  ,   8.77,   1.  ],
       [324.  , 107.  ,   5.  ,   3.5 ,   8.66,   1.  ],
       [322.  , 110.  ,   4.  ,   4.  ,   9.13,   1.  ],
       [308.  , 106.  ,   3.  ,   3.  ,   8.24,   0.  ],
       [310.  , 106.  ,   2.  ,   3.5 ,   8.33,   0.  ],
       [300.  , 102.  ,   2.  ,   1.5 ,   7.87,   0.  ],
       [310.  ,  99.  ,   2.  ,   1.5 ,   7.3 ,   0.  ],
       [340.  , 112.  ,   4.  ,   5.  ,   9.66,   1.  ],
       [321.  , 111.  ,   4.  ,   4.  ,   8.97,   1.  ],
       [336.  , 119.  ,   4.  ,   4.5 ,   9.62,   1.  ],
       [331.  , 115.  ,   5.  ,   4.5 ,   9.36,   1.  ],
       [315.  , 104.  ,   3.  ,   3.  ,   8.33,   0.  ],
       [323.  , 104.  ,   3.  ,   4.  ,   8.44,   1.  ],
       [312.  , 110.  ,   2.  ,   3.5 ,   8.53,   0.  ],
       [324.  , 110.  ,   3.  ,   3.5 ,   9.22,   1.  ],
       [330.  , 115.  ,   5.  ,

In [45]:
from sklearn.preprocessing import MinMaxScaler
scalar=MinMaxScaler()

In [46]:
x_train_sc=scalar.fit_transform(x_train)
x_test_sc=scalar.transform(x_test)

In [47]:
x_train_sc

array([[0.22      , 0.17857143, 0.25      , 0.5       , 0.25      ,
        1.        ],
       [0.88      , 0.96428571, 1.        , 1.        , 0.91911765,
        1.        ],
       [0.3       , 0.71428571, 0.5       , 0.5       , 0.53308824,
        0.        ],
       ...,
       [0.7       , 0.53571429, 0.5       , 0.5       , 0.70220588,
        1.        ],
       [0.72      , 0.67857143, 1.        , 0.875     , 0.74632353,
        1.        ],
       [0.2       , 0.46428571, 0.        , 0.        , 0.22058824,
        0.        ]])

In [48]:
x_test_sc

array([[ 0.44      ,  0.39285714,  0.5       ,  0.625     ,  0.58088235,
         0.        ],
       [ 0.2       ,  0.28571429,  0.5       ,  0.25      ,  0.53676471,
         1.        ],
       [ 0.68      ,  0.71428571,  0.75      ,  0.75      ,  0.57720588,
         1.        ],
       [ 0.68      ,  0.53571429,  1.        ,  0.625     ,  0.53676471,
         1.        ],
       [ 0.64      ,  0.64285714,  0.75      ,  0.75      ,  0.70955882,
         1.        ],
       [ 0.36      ,  0.5       ,  0.5       ,  0.5       ,  0.38235294,
         0.        ],
       [ 0.4       ,  0.5       ,  0.25      ,  0.625     ,  0.41544118,
         0.        ],
       [ 0.2       ,  0.35714286,  0.25      ,  0.125     ,  0.24632353,
         0.        ],
       [ 0.4       ,  0.25      ,  0.25      ,  0.125     ,  0.03676471,
         0.        ],
       [ 1.        ,  0.71428571,  0.75      ,  1.        ,  0.90441176,
         1.        ],
       [ 0.62      ,  0.67857143,  0.75      ,  0.

In [49]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [89]:
model=Sequential()
model.add(Dense(7,activation="relu",input_dim=6))
model.add(Dense(7,activation="relu"))
model.add(Dense(1,activation="linear"))

In [90]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_16 (Dense)            (None, 7)                 49        
                                                                 
 dense_17 (Dense)            (None, 7)                 56        
                                                                 
 dense_18 (Dense)            (None, 1)                 8         
                                                                 
Total params: 113
Trainable params: 113
Non-trainable params: 0
_________________________________________________________________


In [91]:
model.compile(loss='mean_squared_error',optimizer="Adam")

In [92]:
model.fit(x_train_sc,y_train,epochs=100,validation_split=0.2)

Epoch 1/100
8/8 [==============================] - 1s 18ms/step - loss: 0.0766 - val_loss: 0.0572
Epoch 2/100
8/8 [==============================] - 0s 8ms/step - loss: 0.0444 - val_loss: 0.0352
Epoch 3/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0276 - val_loss: 0.0279
Epoch 4/100
8/8 [==============================] - 0s 5ms/step - loss: 0.0221 - val_loss: 0.0281
Epoch 5/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0217 - val_loss: 0.0280
Epoch 6/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0208 - val_loss: 0.0263
Epoch 7/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0196 - val_loss: 0.0241
Epoch 8/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0185 - val_loss: 0.0224
Epoch 9/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0174 - val_loss: 0.0211
Epoch 10/100
8/8 [==============================] - 0s 4ms/step - loss: 0.0165 - val_loss: 0.0198
Epoch 11/100
8/8 [==========

In [93]:
y_pred=model.predict(x_test_sc)

In [94]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.7944177280632334

In [69]:
GRE_SCORE=int(input("Enter Your GRE Score: "))
TOFEL_SCORE=int(input("Enter Your TOFEL Score: "))
UNIVERSITY_RATING=int(input("Enter Your University Rating: "))
SOP=float(input("Enter Statement of Purpose Rating(SOP): "))
CGPA=float(input("Enter Your CGPA: "))
RESEARCH=int(input("Have you did any research ? Please ansewer(YES:1/NO:0)"))

Enter Your GRE Score: 324
Enter Your TOFEL Score: 107
Enter Your University Rating: 4
Enter Statement of Purpose Rating(SOP): 4.0
Enter Your CGPA: 8.87
Have you did any research ? Please ansewer(YES:1/NO:0)1


In [75]:
y_pred=model.predict([[GRE_SCORE,TOFEL_SCORE,UNIVERSITY_RATING,SOP,CGPA,RESEARCH]])
y_pred1=np.where(y_pred>0.5,1,0)
print(y_pred1)

[[1]]


In [76]:
if y_pred1==1:
  print("Granted for GRE Addmission..")
if y_pred1==0:
  print("Not Granted for GRE Addmission..")

Granted for GRE Addmission..
